# Form implementation generated from reading ui file '/media/nemsys/data/projects/courses/netIT/PythonCourseNetIT/PythonCourse_15.08.2023-Labs/lab40/Test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.btnOK = QtWidgets.QPushButton(parent=Form)
        self.btnOK.setGeometry(QtCore.QRect(20, 10, 161, 41))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(parent=Form)
        self.btnCancel.setGeometry(QtCore.QRect(20, 70, 161, 41))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnOK.setText(_translate("Form", "OKOKOKOK"))
        self.btnCancel.setText(_translate("Form", "Cancel"))
